// Supabase Storage — Cash Handling receipt / deposit-slip photos only
// (Phase 2). Nothing else in this codebase touches Supabase Storage;
// everything else talks to Postgres directly via server/db.js's raw `pg`
// pool. Kept as its own small module rather than folded into
// cashhandling.js so the "talks to an external service, not just our own
// DB" boundary stays obvious.
//
// Uses the SERVICE ROLE key deliberately, matching this project's
// standing pattern of "trusted server-side code bypasses RLS/policy,
// authorization is enforced in Express" (server/db.js's
// barplatform_service / withServiceClient). The bucket itself
// (`cash-receipts`) is private with zero storage.objects policies, so the
// service role key is the ONLY way in or out — there is no anon/client
// path to this bucket at all, by design. A receipt is only ever handed to
// a browser as a short-lived signed URL minted here, never as a public
// URL or a raw bucket path.
const { createClient } = require('@supabase/supabase-js');

const BUCKET = 'cash-receipts';
const SIGNED_URL_TTL_SECONDS = 300; // 5 minutes — minted fresh on every request, not cached

let client = null;
function getClient() {
  if (client) return client;
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    // Thrown lazily (on first real use) rather than at require-time, so
    // the server still boots fine in local/dev setups that never touch
    // Cash Handling transactions — same reasoning as this codebase's
    // other optional integrations (Twilio, nodemailer) failing soft until
    // actually used rather than crashing at startup. statusCode 500: this
    // is a server misconfiguration, never something the caller can fix by
    // changing their request.
    throw Object.assign(
      new Error('SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are not set — receipt upload/retrieval is unavailable until both are configured.'),
      { statusCode: 500 }
    );
  }
  client = createClient(url, key, { auth: { persistSession: false } });
  return client;
}

const EXT_BY_MIME = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/heic': 'heic',
  'image/webp': 'webp',
  'application/pdf': 'pdf',
};

function extensionFor(mimetype) {
  return EXT_BY_MIME[mimetype] || 'bin';
}

// transactionId is generated by the caller (crypto.randomUUID()) BEFORE
// the cash_transactions row is inserted, so the object path is known
// up front and the row can be written in one INSERT with receipt_path
// already populated — no "insert then patch" two-step, no orphaned row
// if the upload fails partway (the INSERT just never happens).
async function uploadReceipt({ buffer, mimetype, transactionId, locationId }) {
  const ext = extensionFor(mimetype);
  const path = `${locationId}/${transactionId}.${ext}`;
  const { error } = await getClient().storage.from(BUCKET).upload(path, buffer, {
    contentType: mimetype,
    upsert: false, // a transaction id is only ever used once; a collision means something is wrong, don't silently overwrite
  });
  if (error) throw Object.assign(new Error(`Receipt upload failed: ${error.message}`), { statusCode: 500 });
  return path;
}

async function getSignedReceiptUrl(path) {
  const { data, error } = await getClient().storage.from(BUCKET).createSignedUrl(path, SIGNED_URL_TTL_SECONDS);
  if (error) throw Object.assign(new Error(`Could not create a signed receipt URL: ${error.message}`), { statusCode: 500 });
  return data.signedUrl;
}

module.exports = { uploadReceipt, getSignedReceiptUrl, EXT_BY_MIME };
