// Supabase Storage — the only two things in this codebase that live
// outside Postgres: Cash Handling receipt / deposit-slip photos
// (Phase 2) and applicants' optional profile photos (patch_031).
// Everything else talks to Postgres directly via server/db.js's raw `pg`
// pool. Kept as its own small module rather than folded into
// cashhandling.js / employees.js so the "talks to an external service,
// not just our own DB" boundary stays obvious.
//
// Uses the SERVICE ROLE key deliberately, matching this project's
// standing pattern of "trusted server-side code bypasses RLS/policy,
// authorization is enforced in Express" (server/db.js's
// barplatform_service / withServiceClient). Both buckets
// (`cash-receipts`, `people-photos`) are private with zero
// storage.objects policies, so the service role key is the ONLY way in
// or out — there is no anon/client path to either bucket at all, by
// design. A file is only ever handed to a browser as a short-lived
// signed URL minted here, never as a public URL or a raw bucket path.
const crypto = require('crypto');
const { createClient } = require('@supabase/supabase-js');

const RECEIPTS_BUCKET = 'cash-receipts';
const PHOTOS_BUCKET = 'people-photos';
const SIGNED_URL_TTL_SECONDS = 300; // 5 minutes — minted fresh on every request, not cached

let client = null;
function getClient() {
  if (client) return client;
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    // Thrown lazily (on first real use) rather than at require-time, so
    // the server still boots fine in local/dev setups that never touch
    // Cash Handling transactions — same reasoning as this codebase's
    // other optional integrations (Twilio, nodemailer) failing soft until
    // actually used rather than crashing at startup. statusCode 500: this
    // is a server misconfiguration, never something the caller can fix by
    // changing their request.
    throw Object.assign(
      new Error('SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are not set — file upload/retrieval is unavailable until both are configured.'),
      { statusCode: 500 }
    );
  }
  client = createClient(url, key, { auth: { persistSession: false } });
  return client;
}

const EXT_BY_MIME = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/heic': 'heic',
  'image/webp': 'webp',
  'application/pdf': 'pdf',
};

// The subset a profile photo may be — mirrors the people-photos bucket's
// allowed_mime_types (patch_031). Checked in Express before the upload
// is attempted so the applicant gets a plain message instead of a
// storage error.
const PHOTO_MIMES = ['image/jpeg', 'image/png', 'image/heic', 'image/webp'];

function extensionFor(mimetype) {
  return EXT_BY_MIME[mimetype] || 'bin';
}

// A browser reports the mimetype it *thinks* a file has (usually from the
// extension) — good enough to pick a file extension, not good enough to
// trust on a public, unauthenticated endpoint. This peeks at the leading
// bytes so a renamed script can't be stored under image/jpeg. HEIC is an
// ISO-BMFF container: 'ftyp' at offset 4 (the brand after it varies:
// heic, heix, mif1, ...). Not a full parser, just a sanity check.
function looksLikeImage(buffer, mimetype) {
  if (!buffer || buffer.length < 12) return false;
  switch (mimetype) {
    case 'image/jpeg': return buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff;
    case 'image/png': return buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
    case 'image/webp': return buffer.subarray(0, 4).toString('ascii') === 'RIFF' && buffer.subarray(8, 12).toString('ascii') === 'WEBP';
    case 'image/heic': return buffer.subarray(4, 8).toString('ascii') === 'ftyp';
    default: return false;
  }
}

async function uploadTo(bucket, path, buffer, mimetype, what) {
  const { error } = await getClient().storage.from(bucket).upload(path, buffer, {
    contentType: mimetype,
    upsert: false, // an id is only ever used once; a collision means something is wrong, don't silently overwrite
  });
  if (error) throw Object.assign(new Error(`${what} upload failed: ${error.message}`), { statusCode: 500 });
  return path;
}

async function signedUrlFor(bucket, path, what) {
  const { data, error } = await getClient().storage.from(bucket).createSignedUrl(path, SIGNED_URL_TTL_SECONDS);
  if (error) throw Object.assign(new Error(`Could not create a signed ${what} URL: ${error.message}`), { statusCode: 500 });
  return data.signedUrl;
}

// ---- Cash Handling receipts ------------------------------------------
// transactionId is generated by the caller (crypto.randomUUID()) BEFORE
// the cash_transactions row is inserted, so the object path is known
// up front and the row can be written in one INSERT with receipt_path
// already populated — no "insert then patch" two-step, no orphaned row
// if the upload fails partway (the INSERT just never happens).
async function uploadReceipt({ buffer, mimetype, transactionId, locationId }) {
  const ext = extensionFor(mimetype);
  return uploadTo(RECEIPTS_BUCKET, `${locationId}/${transactionId}.${ext}`, buffer, mimetype, 'Receipt');
}

async function getSignedReceiptUrl(path) {
  return signedUrlFor(RECEIPTS_BUCKET, path, 'receipt');
}

// ---- People photos ---------------------------------------------------
// Same id-first shape as receipts: employees.createPendingEmployee mints
// the person's uuid, uploads, then INSERTs with photo_path set. Objects
// live in a per-person folder under a random name, so replacing a photo
// from My Account is upload-new / point the row at it / delete-old, and
// never an overwrite of an object a signed URL might still be serving.
async function uploadPersonPhoto({ buffer, mimetype, personId }) {
  const ext = extensionFor(mimetype);
  return uploadTo(PHOTOS_BUCKET, `${personId}/${crypto.randomUUID()}.${ext}`, buffer, mimetype, 'Photo');
}

async function getSignedPersonPhotoUrl(path) {
  return signedUrlFor(PHOTOS_BUCKET, path, 'photo');
}

// Best-effort: called when a pending applicant is discarded so the
// bucket doesn't keep a photo of someone who was never hired. A failure
// here is logged, not surfaced — the people row is already gone and
// that's the part that matters to the manager.
async function deletePersonPhoto(path) {
  if (!path) return;
  const { error } = await getClient().storage.from(PHOTOS_BUCKET).remove([path]);
  if (error) console.warn(`[storage] could not delete photo ${path}: ${error.message}`);
}

module.exports = {
  uploadReceipt, getSignedReceiptUrl,
  uploadPersonPhoto, getSignedPersonPhotoUrl, deletePersonPhoto, looksLikeImage, PHOTO_MIMES,
  EXT_BY_MIME,
};
